var Product = require('../models/product');
var mongodb = require('mongodb');
var MongoClient = require('mongodb').MongoClient;  // connect online
var uri = "mongodb+srv://dat:vippergod12@data-imllf.mongodb.net/test"; // connect online

// var mongoose = require('mongoose');
// mongoose.connect('mongodb://localhost:27017/shopping');

var product = [
	new Product({
		name : 'Bài UNO Đại Chiến (Loại Dày)',
		ID : 'mebe1',
		price : 55000,
		type : 'mebe',
		info : 'Trò Chơi Boardgame',
		link : 'baiuno',
		url : '0',
		status : 10,
	}),
	new Product({
		name : 'Sữa Bột Abbott Similac Eye-Q2 (400g)',
		ID : 'mebe2',
		price : 250000,
		type : 'mebe',
		info : 'Sản phẩm dành cho bé từ 6 - 12 tháng tuổi\nVitamin A, C, E và Prebiotic hỗ trợ miễn dịch cho trẻ\nHệ dưỡng chất chứa AA, DHA, Omega 3, Omega 6... giúp phát triển não bộ và thị giácHệ chất béo không chứa dầu cọ giúp tăng cường hấp thu canxi',
		link : 'sua',
		url : '0',
		status : 20,
	}),
	new Product({
		name : 'Gối Đa Năng Tai Voi Dành Cho Bé',
		ID : 'mebe3',
		price : 259000,
		type : 'mebe',
		info : 'Thiết kế theo hình cong tiện dụng giúp các bà mẹ mang bầu dựa lưng, kê khi ngủ, hay nâng đỡ lưng bé\nGối tai voi hạn chế bé ngủ nghiêng một bên, chống móp đầu cho bé\nMàu sắc nhẹ nhàng kết hợp với họa tiết đáng yêu làm điểm nhấn',
		link : 'sua',
		url : '0',
		status : 20,
	}),
	new Product({
		name : 'Máy Xay Cầm Tay Standard',
		ID : 'mebe4',
		price : 455000,
		type : 'mebe',
		info : 'Xay nhuyễn, mịn với công suất 700W. Lưỡi và cán dao với chất liệu thép không gỉ an toàn.Có nhiều cấp độ để điều chỉnh phù hợp',
		link : 'mayxay',
		url : '0',
		status : 10,
	}),
	new Product({
		name : 'Dầu Tràm Nguyên Chất Hoàng Cung Huế',
		ID : 'mebe5',
		price : 168000,
		type : 'mebe',
		info : 'Được chưng cất, chiết xuất từ lá cây tràm gió. An toàn với trẻ sơ sinh, phụ nữ mang thai, người già, trẻ nhỏ. Giúp giữ ấm cơ thể, phòng ho, tránh gió, cảm lạnh ',
		link : 'dautram',
		url : '0',
		status : 10,
	}),
	new Product({
		name : 'Điện Thoại Samsung Galaxy S9 Plus',
		ID : 'dientu1',
		price : 20190000,
		type : 'dientu',
		info : 'Điện thoại chính hãng, Nguyên seal, Mới 100%, Chưa Active. Miễn phí giao hàng toàn quốc, Thiết kế: Nguyên khối, màn hình vô cực, Tính năng: Chống nước, chống bụi đạt chuẩn IP68',
		link : 's9',
		url : '0',
		status : 10,
	}),
	new Product({
		name : 'Điện Thoại Samsung Galaxy Note 8 SM-N950U',
		ID : 'dientu2',
		price : 15190000,
		type : 'dientu',
		info : 'Điện thoại chính hãng, Nguyên seal, Mới 100%, Chưa Active. Miễn phí giao hàng toàn quốc, Thiết kế: Nguyên khối, màn hình vô cực, Tính năng: Chống nước, chống bụi đạt chuẩn IP68',
		link : 'note8',
		url : '0',
		status : 10,
	}),
	new Product({
		name : 'Macbook Pro 2017 MPTR2 (15.4 inch) ',
		ID : 'dientu3',
		price : 54190000,
		type : 'dientu',
		info : 'Chip: Intel Core i7 Quad-Core. RAM: 16GB. Ổ cứng: 256GB SSD. Chipset đồ họa: AMD Radeon Pro 555 Graphics (2GB GGDR5). Màn hình: 15.4 inch Retina (2880 x 1800 pixels). Pin: Li-Po 76 Wh',
		link : 'macbook',
		url : '0',
		status : 10,
	}),
	new Product({
	    name: 'Laptop Dell Vostro 5471 VTI5207W',
	    ID: 'dientu4',
	    price: 16190000,
	    type: 'dientu',
	    info: 'Chip: Intel Core i5-8250. RAM: 4GB DDR4 2133Mhz. Ổ cứng: 1TB HDD. Chipset đồ họa: Intel UHD Graphics 620. Màn hình: 14 inch Full HD (1920 x 1080) Anti-Glare LED-Backlit',
	    link: 'dell',
	    url: '0',
	    status: 10,
	}),
	new Product({
	name: 'Xe Máy Honda Blade 2018 - Phanh Đĩa, Vành Nan Hoa - Đỏ',
    	ID: 'xe1',
    	price: 19190000,
    	type: 'xe',
    	info: 'Giá bán xe đã bao gồm thuế VAT, không bao gồm thuế trước bạ và chi phí làm giấy tờ, biển số',
    	link: 'blade',
    	url: '0',
	   	status: 10,
	 }),
	 new Product({
	     name: 'Xe Máy Yamaha Exciter 150 Limited',
			 ID: 'xe2',
			 price: 52000000,
			 type: 'xe',
			 info: 'Giá bán xe đã bao gồm thuế VAT, không bao gồm thuế trước bạ và chi phí làm giấy tờ, biển số',
			 link: 'exciter',
			 url: '0',
			 status: 10,
		}),
		new Product({
				name: 'Xe Máy Honda SH Mode Phiên Bản Cá Tính 2018',
				ID: 'xe3',
				price: 68000000,
				type: 'xe',
				info: 'Giá bán xe đã bao gồm thuế VAT, không bao gồm thuế trước bạ và chi phí làm giấy tờ, biển số',
				link: 'sh',
				url: '0',
				status: 10,
		 }),
		 new Product({
				 name: 'Xe Máy Honda Vision 2018 Phiên Bản Cao Cấp',
				 ID: 'xe4',
				 price: 35000000,
				 type: 'xe',
				 info: 'Giá bán xe đã bao gồm thuế VAT, không bao gồm thuế trước bạ và chi phí làm giấy tờ, biển số',
				 link: 'vision',
				 url: '0',
				 status: 10,
			}),
			new Product({
					name: 'Combo Túi Messenger Glado DCG026GR + Giày Sneaker Nam GZ020WH',
					ID: 'fashion1',
					price: 218000,
					type: 'fashion',
					info: 'Bộ túi + giày sneaker nam trẻ trung, năng động. Chất liệu bền chắc, dễ vệ sinh. Màu sắc đơn giản, dễ phối đồ',
					link: 'giay',
					url: '0',
					status: 10,
			 }),
			 new Product({
 					name: 'Kính Mát Nữ Swarovski SW9044 01B - Xám Đen',
 					ID: 'fashion2',
 					price: 7438000,
 					type: 'fashion',
 					info: 'Gọng kim loại bền bỉ, cứng cáp và chống chịu va đập. Trọng lượng nhẹ, ôm sát gương mặt thoải mái. Chống tia tử ngoại, tia UV giúp bảo vệ mắt tốt hơn',
 					link: 'kinh',
 					url: '0',
 					status: 10,
 			 }),
			 new Product({
 					name: 'Lắc Chân Cỏ Bốn Lá Showfay Jewelry TA0014 - Bạc',
 					ID: 'fashion3',
 					price: 78000,
 					type: 'fashion',
 					info: 'Thiết kế tinh xảo, độc đáo. Dễ dàng phối với nhiều loại trang phục. Chất liệu hợp kim bạc 925 và Copper. Đá Zircon nhân tạo',
 					link: 'lac',
 					url: '0',
 					status: 10,
 			 }),
			 new Product({
 					name: 'Balo PRAZA BL158XAM (32 x 43 cm) - Xám',
 					ID: 'fashion4',
 					price: 767000,
 					type: 'fashion',
 					info: 'Chất liệu vải Polyester bền chắc, hạn chế sờn rách. Không gian chứa rộng rãi, nhiều ngăn lớn nhỏ tiện lợi. Quai đeo có lớp đệm mút chống đau vai. Đường may tỉ mỉ, tăng tuổi thọ sản phẩm',
 					link: 'balo',
 					url: '0',
 					status: 10,
 			 }),
			 new Product({
 					name: 'Bình Giữ Nhiệt Lock&Lock Colorful Tumbler Funcolor LHC3222 ',
 					ID: 'giadung1',
 					price: 359000,
 					type: 'giadung',
 					info: 'Chất liệu thép không gỉ 304 đồng nhất và trang bị lớp chân không nên lực giữ nhiệt tốt. Thiết kế với màu sắc trang nhã, tinh tế',
 					link: 'binhnuoc',
 					url: '0',
 					status: 10,
 			 }),
			 new Product({
 					name: 'Đèn Bàn LED Chống Cận Tiross TS1804 - 6W',
 					ID: 'giadung2',
 					price: 349000,
 					type: 'giadung',
 					info: 'Công nghệ đèn LED tiết kiệm điện. Thân đèn có khả năng uốn dẻo 306 độ. Lỗ cắm tháo lắp linh hoạt, tiện trong quá trình di chuyển',
 					link: 'den',
 					url: '0',
 					status: 10,
 			 }),
			 new Product({
 					name: 'Bộ Ga Bọc JAHVIER Akemi - VDB65794JAH - 1m6x2m',
 					ID: 'giadung3',
 					price: 500000,
 					type: 'giadung',
 					info: 'Dễ chịu khi tiếp xúc. Bền màu, thấm hút tốt. Không xù lông. Không gây dị ứng',
 					link: 'chan',
 					url: '0',
 					status: 10,
 			 }),
			 new Product({
 					name: 'Ghế Sofa Góc 3 Chỗ Kivik KOZOKA - Xám',
 					ID: 'giadung4',
 					price: 20329000,
 					type: 'giadung',
 					info: 'Kiểu dáng đơn giản, sang trọng với gam màu xám tinh tế. Khung ghế được làm bằng ván ép, gỗ tạp chất lượng cao và bền bỉ',
 					link: 'sofa',
 					url: '0',
 					status: 10,
 			 }),
];

MongoClient.connect(uri, function(err, db)
{
  if (err) throw err;
    var dbo = db.db("3dwebsite");
		for(var i = 0; i< product.length; i++)
	    dbo.collection("product").insertOne(product[i], function(err, res)
			{
	      if (err) throw err;
	    });
		db.close();
		console.log("document inserted");
});
